import type { Metadata } from "next";
import "../globals.css";

import { Header } from "@/components/shared";

export const metadata: Metadata = {
  title: "Next Pizza | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <main className="min-h-screen">
         <Header />
         {children}
      </main>
  );
}
